[package]
name = "contributor_checker"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = "4.5.29"
tokio = { version = "1.43.0", features = ["rt", "rt-multi-thread", "macros"] }
reqwest = { version = "0.12.12", features = ["json"] }
serde_json = "1.0.138"
chrono = "0.4.39"
colored = "2.0"